

// == ERRORS ==
// ERR_NEEDMOREPARAMS
// ERR_INVITEONLYCHAN
// ERR_CHANNELISFULL
// ERR_NOSUCHCHANNEL
// ERR_BANNEDFROMCHAN
// ERR_BADCHANNELKEY
// ERR_BADCHANMASK
// ERR_TOOMANYCHANNELS

// == REPLIES ==
// RPL_TOPIC